### ISSUE TITLE
Should we add steps to run the collector?

### ISSUE THREAD

**Issue by emdneto** [joaopgrassi/otel-recipes#188]
This is not a bug issue at all, but I just noticed in all recipes we are using otel-collector to receive telemetry data and we don't mention it in any step.  My concern is about if we should create reproducible steps user can follow to get same result we are providing on the recipe by just copying and paste. 

So, the purpose of this issue is to discuss if we should also add steps to run the collector or not (maybe using docker). If so we can think in a way to improve that in each recipe.

**Comment by joaopgrassi** [comment]
That's a good point, the samples require a collector but it's never mentioned how to get that one running.

I think thought we can solve that easily. We just need to add steps (probably first) to start the collector. One thing we don't have is a way to define an "inline" step - such that we could put the docker command and it would be displayed in the website. But that's also easy to fix.

I will try to break this down since there's multiple tasks involved, then we can work on them in parallel.

**Comment by jamesylgan** [comment]
+1. This is great, but add in complications around how to configure the collector (Official otel docs are _**really long**_ for what is essentially "how do I get to the point where I can instrument an app using the recipes" and sometimes only have proper documentation in the specification)

**Comment by jamesylgan** [comment]
In the mean-time, I figure y'all would know, does anyone have a good example of "MVP" collector config to get one of the metrics examples running?

**Comment by emdneto** [comment]
> +1. This is great, but add in complications around how to configure the collector (Official otel docs are _**really long**_ for what is essentially "how do I get to the point where I can instrument an app using the recipes" and sometimes only have proper documentation in the specification)

I think for most of recipes a simple `docker run -p 4317:4317 otel/opentelemetry-collector-contrib:0.99.0` will work. 

Maybe we can think collector is also a dependency and define the version in recipefile.json to interpolate it in the command during rendering on the website. In cases we need custom collector config we can provide the config in a expandable code block so user can copy and run the command like this `docker run -v $(pwd)/config.yaml:/etc/otelcol-contrib/config.yaml -p 4317:4317 otel/opentelemetry-collector-contrib:0.99.0`.

**Comment by joaopgrassi** [comment]
> In the mean-time, I figure y'all would know, does anyone have a good example of "MVP" collector config to get one of the metrics examples running?

@jamesylgan inside each recipe you can find the collector config for that example. All of them will export via HTTP to our local "dummy" OTLP server but you get an idea on what to configure to change to any other otlp backend.

**Comment by joaopgrassi** [comment]
@emdneto thanks for reporting this! 

I refined this a bit and opened a grouping issue #194. Closing this as triage accepted. Development should occur within that epic.
